---
- name: Setup EJBCA using Docker Compose
  hosts: ejbca
  become: yes
  tasks:
    - name: Ensure Docker is installed
      include_role:
        name: geerlingguy.docker

    - name: Install Docker Compose
      command:
        cmd: "curl --http1.1 -L 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)' -o /usr/local/bin/docker-compose"
      args:
        creates: /usr/local/bin/docker-compose
      become: yes

    - name: Make Docker Compose executable
      file:
        path: /usr/local/bin/docker-compose
        mode: "0755"
      become: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - containers/datadbdir

    - name: Create docker-compose.yml for EJBCA setup
      copy:
        dest: containers/docker-compose.yml
        content: |
          version: '3'
          networks:
            access-bridge:
              driver: bridge
            application-bridge:
              driver: bridge
          services:
            ejbca-database:
              container_name: ejbca-database
              image: "library/mariadb:latest"
              networks:
                - application-bridge
              environment:
                - MYSQL_ROOT_PASSWORD=foo123
                - MYSQL_DATABASE=ejbca
                - MYSQL_USER=ejbca
                - MYSQL_PASSWORD=ejbca
              volumes:
                - ./datadbdir:/var/lib/mysql:rw
            ejbca-node1:
              hostname: ejbca-node1
              container_name: ejbca
              image: keyfactor/ejbca-ce:latest
              depends_on:
                - ejbca-database
              networks:
                - access-bridge
                - application-bridge
              environment:
                - DATABASE_JDBC_URL=jdbc:mariadb://ejbca-database:3306/ejbca?characterEncoding=UTF-8
                - LOG_LEVEL_APP=INFO
                - LOG_LEVEL_SERVER=INFO
                - TLS_SETUP_ENABLED=simple
              ports:
                - "80:8080"
                - "443:8443"

    - name: Start EJBCA containers
      command:
        cmd: "docker compose up -d"
        chdir: /root/containers/
      register: compose_up_output

    #    - name: Wait for port 443 to be available
    #      wait_for:
    #        port: 443
    #        timeout: 300
    #        delay: 5
    #      delegate_to: localhost

    - name: Wait for EJBCA to start
      uri:
        url: "https://ejbca-node1:443/ejbca/adminweb/"
        method: GET
        validate_certs: no # Since the certificate is self-signed
        return_content: yes
      register: result
      until: "'EJBCA Administration' in result.content"
      retries: 30 # You can adjust the number of retries as needed
      delay: 10 # Wait for 10 sec between retries
      delegate_to: localhost

    - name: Show logs (this task is optional)
      command:
        cmd: "docker-compose logs -f"
        chdir: containers/
      register: logs_output
      ignore_errors: true

    - debug:
        var: logs_output.stdout_lines
